FORMAT:v1
HOST: https://highnoon-dev.appspot.com/_ah/api/highnoon/v1

# How to Play

> Win by eliminating McCree before he defeats you

- Create a Player account and join a Game

- Choose to `pursue`, `retreat` or `showdown` in each round against McCree

- McCree will make his own choice and compare it against yours

- After each round McCree takes damage or gains progress towards High Noon

> McCree starts with 200 health and takes between `20 to 70` damage per successful attack

## The Choice

Each choice is strong against one of McCree's choices:

- Pursuing while he Retreats
- Retreating while he is in Showdown
- Showdown while he Pursues

If both you and McCree make the same choice, the round ends in a stalemate

## High Noon

Each round, McCree will gain an amount of progress towards triggering his ultimate. 

> If McCree chooses a strong choice against you, he gains more progress. ability - `High Noon`

When High Noon is used, is has a chance of instantly defeating you

> End it fast! A longer match will make the odds of losing to High Noon more likely

## Create a new Player [/player/new]
 
Join the battle, optionally choosing a name

### Create a new player [POST]

+ Request (application/json)

        {
            "desired_name":"Roland"
        }

+ Response 200 (application/json)
        
        {
            "player_id": '31337',
            "player_name" :'Roland'
        }

+ Response 400 (text/plain)

        player_name was not valid (perhaps it contained profanity)
        
    
    
## Starting a Game [/game/new]

Create a new match, 1 vs 1 with our favorite gunslinger

### Start a new game [POST]

+ Request (application/json)

        {
            "player_id":"31337",
            "rival_id": "8989"
        }

+ Response 200 (application/json)

        { 
            "game_id": '42',
            "player_id" : '31337',
             "hand" : {
                "player_id" : '31337' 
                "cards": [ {value: '2', suit:'diamonds'}]
        }

+ Response 400 (text/plain)

        specified player_id not found

## Getting information about a Game [/game/status/{game_id}]

### Get game status by ID [GET]

Get information about the state of a game


+ Parameters
    + game_id (required, number) - unique ID for the game


+ Response 200 (application/json)

        { 
            "game_id": '42',
            "player_id" : '31337',
             "hand" : {
                "player_id" : '31337' 
                "cards": [ {value: '2', suit:'diamonds'}]
        }

+ Response 400 (text/plain)

        specified game_id not found


## Cancelling a Game [/game/cancel/{game_id}]

### Cancel a Game by ID [GET]

Remove a game that's in progress

> completed games cannot be removed


+ Parameters
    + game_id (required, number) - unique ID for the game


+ Response 200 (application/json)

        { 
            "game_id": '42',
            "winner_id": 'None',
            "winner_name": 'None'
        }

+ Response 400 (text/plain)

        specified game_id not found

+ Response 403 (text/plain)

        that game is finished and cannot be modified


## Playing the Game [/game/play/{game_id}{?player_id}]

Make a move or check the current game state

### Look at your Hand [GET]
Get game status, your current hand and current card choice 

Possible values of `status`:
- `ready` = you may choose a card for the next round 
- `waiting` = opponent has not chosen a card yet
- `showdown` = server is processing the results of the last round
- `ended` = game is over

+ Parameters
    + game_id (required, number) - unique ID for the game
    + player_id (required, number) - player ID requesting 
     
+ Response 200 (application/json)

        { 
            "game_id": "42",
            "status" : "waiting"
            "choice" : "2"
            "hand" : {
                "player_id" : '31337' 
                "cards": [ {value: '2', suit:'diamonds'}]
                }
            
        }  
    
+ Response 401 (text/plain)

        player_id was invalid for the provided game
        
+ Response 403 (text/plain)

        that game is finished and cannot be modified

### Play a Card [POST]
Choose a card value to play from your hand

> This choice can be freely changed until both players have chosen their card for this round

Choosing to play the Ace of Spades will discard any card value while *also* discarding the opponent's card(s)

+ Request (application/json)

        {
        
            "game_id": '42',
            "player_id": '31337',
            "card": '7',
            "ace": 'True'
        }

+ Response 200 (application/json)

        Once both players have chosen a card value, the server resolves the showdown and updates each player's hand

+ Response 401 (text/plain)

        player_id was invalid for the provided game_

+ Response 402 (text/plain)

        showdown is in progress, please wait until game `status` is `ready`

+ Response 403 (text/plain)

        player_id does not have the selected card