FORMAT:v1
HOST: https://highnoon-dev.appspot.com/_ah/api/highnoon/v1

# How to Play

> Win by eliminating McCree before he defeats you

- Create a Player account and join a Game

- Choose an action: `pursue`, `retreat` or `showdown` in each round against McCree

- McCree takes his action *after* yours

- Based on your choices, McCree will take damage or gain progress towards High Noon

> McCree starts with 200 health and takes between `20 to 30` damage per successful attack

## The Choice

Each choice is strong against one of McCree's choices:

- Pursuing while he Retreats
- Retreating while he is in Showdown
- Showdown while he Pursues

If both you and McCree make the same choice, the round ends in a stalemate

## High Noon

Each round, McCree will gain an amount of progress towards triggering his ultimate ability `High Noon`

> If McCree chooses a strong choice against you, he gains more progress

When High Noon is used, is has a chance of instantly defeating you

> In later rounds the odds of losing to High Noon become more likely

Since McCree takes his action after yours, you can defeat him at the last second if his health is low and you damage him before he's able to trigger `High Noon`

## Create a new Player [/player/new]
 
Join the battle, optionally choosing a name and setting your email

### Create a new player [POST]

+ Request (application/json)

        {
            "desired_name":"Roland",
            "email":"roland@tet.corp"
        }

+ Response 200 (application/json)
        
        {
            "player_id": '31337',
            "player_name" :'Roland'
        }

+ Response 400 (text/plain)

        player_name was not valid (perhaps it contained profanity)
        
    
    
## Starting a Game [/game/new]

Create a new match, 1 vs 1 with our favorite gunslinger

### Start a new game [POST]

+ Request (application/json)

        {
            "player_id":"31337"
        }

+ Response 200 (application/json)

        { 
            "game_id": "42",
            "player_id" : "31337"

        }

+ Response 400 (text/plain)

        specified player_id not found

## Getting information about a Game [/game/status/{game_id}]

### Get game status by ID [GET]

Get information about the state of a game


+ Parameters
    + game_id (required, number) - unique ID for the game


+ Response 200 (application/json)

        { 
            "game_id": '42',
            "player_id" : '31337'
        }

+ Response 400 (text/plain)

        specified game_id not found

## Getting a list of Games for a given Player [/game/list/{player_id}]

### Get list of games by player ID [GET]

Get all games in progress for a specified player


+ Parameters
    + player_id (required, number) - unique ID for the player


+ Response 400 (text/plain)

        specified player_id not found



## Cancelling a Game [/game/cancel/{game_id}]

### Cancel a Game by ID [GET]

Remove a game that's in progress

> completed games cannot be removed


+ Parameters
    + game_id (required, number) - unique ID for the game


+ Response 200 (application/json)

        { 
            "game_id": '42'
        }

+ Response 400 (text/plain)

        specified game_id not found

+ Response 403 (text/plain)

        that game is finished and cannot be modified


## Playing the Game [/game/play]

Make a move against McCree


### Choose an Action [POST]

Choose an action: `pursue`, `retreat` or `showdown` 

> If `won` is returned True, you won! (The inverse... not so much)

McCree will then choose an action and respond with his updated health total and his action

Each choice is strong against one of McCree's choices:

- Pursuing while he Retreats
- Retreating while he is in Showdown
- Showdown while he Pursues

If both you and McCree make the same choice, the round ends in a stalemate

> You may wish to combine the `watch` with `-n 3` along with `curl` to simulate a running battle

+ Request (application/json)

        {
            "game_id": "42",
            "player_id": "31337",
            "action":"pursue"
        }

+ Response 200 (application/json)

        {
            "game_id": "42",
            "player_id": "31337",
            "health": "100",
            "action": "retreat"
            "won" : "True"
        }

+ Response 400 (text/plain)

        that action is not a possible choice

+ Response 400 (text/plain)

        specified game_id not found
        
+ Response 400 (text/plain)

        specified player_id not found

+ Response 401 (text/plain)

        specified player_id not valid for this game
        
+ Response 403 (text/plain)

        that game is finished