FORMAT:v1
HOST: https://aceofblades-dev.appspot.com/_ah/api/aceofblades/v1

# Ace of Blades
Take a regular deck and remove all face cards, leave only the ace of spades and numbered cards (37 total)

Start each player with starts with 5 cards from a shuffled deck

## The Choice
Each round, players choose a single card value to play (i.e. "all my 9's" or "three of my 4's")

> You may play choose to play multiple cards with the same value with no advantage or downside (discarding all of them)

## The Showdown

Card values are compared and judged:
- Discard all cards of the lowest value
- If all cards are the same value, they are all discarded
- If the Ace of Spades was played, all cards are discarded

If either player has the Ace of Spades, they may play it and choose any card value to discard

> After playing the Ace, it transfers to the opposing player

## The Aftermath
After the showdown, both players draw a card from the shuffled deck

> Win by discarding your entire hand, or having the fewest cards when the draw pile is empty
 
## Create a new Player [/user/]
 
Join and become a player

### Create a new player [POST]

+ Request (application/json)

        {
            "desired_name":"Roland"
        }

+ Response 200 (application/json)
        
        {
            "player_id": '31337',
            "player_name" :'Roland'
        }

+ Response 400 (text/plain)

        player_name was not valid (perhaps it contained profanity)
        
    
    
## Starting a New Game [/game/{player_id}{?rival_id}]

Start a fight, and leave it open or immediately challenge another player

+ Parameters
    + player_id (required, number) - unique ID for player creating the game
    + rival_id (optional, number) - unique ID for opponent player to challenge

### Start a new game [GET]
+ Response 200 (application/json)

        { 
            "game_id": '42',
            "player_id" : '31337',
             "hand" : {
                "player_id" : '31337' 
                "cards": [ {value: '2', suit:'diamonds'}]
        }

+ Response 400 (text/plain)

        specified player_id not found

## Playing the Game [/play/{game_id}{?player_id,card,ace}]

Make a move or check the current game state

### Show your Hand [GET]
Get game status, your current hand and current card choice 

Possible values of `status`:
- `ready` = you may choose a card for the next round (`choice` will be None in this case)
- `waiting` = opponent has not chosen a card yet
- `showdown` = server is processing the results of the last round
- `ended` = game is over

+ Parameters
    + game_id (required, number) - unique ID for the game
    + player_id (required, number) - player ID requesting 
     
+ Response 200 (application/json)

        { 
            "game_id": "42",
            "status" : "waiting"
            "choice" : "2"
            "hand" : {
                "player_id" : '31337' 
                "cards": [ {value: '2', suit:'diamonds'}]
                }
            
        }  
    
+ Response 401 (text/plain)

        player_id was invalid for the provided game
        
+ Response 402 (text/plain)

        This game has ended

### Play a Card [POST]
Choose a card value to play from your hand

> This choice can be freely changed until both players have chosen their card for this round

Choosing to play the Ace of Spades will discard any card value while *also* discarding the opponent's card(s)


+ Parameters
    + game_id (required, number) - unique ID for the game
    + player_id (required, number) - your unique player ID
    + card (required, number) - the card value you wish to play
    + ace (optional, boolean) - whether you want to play the ace of spades
    
+ Request (application/json)

        {
        
            "game_id": '42',
            "player_id": '31337',
            "card": '7',
            "ace": 'True'
        }

+ Response 200 (application/json)

        Once both players have chosen a card value, the server resolves the showdown and updates each player's hand

+ Response 401 (text/plain)

        player_id was invalid for the provided game_

+ Response 402 (text/plain)

        showdown is in progress, please wait until game `status` is `ready`

+ Response 403 (text/plain)

        player_id does not have the selected card