application: aceofblades-dev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# TODO - add endpoint handlers for defined functions 
# ASK - can we redefine this to a different baseurl? i.e. /
- url: /_ah/spi/.*
  script: api.api


libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest